INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_1", "music", 100000, "2017-02-03", "2017-04-03");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_2", "art", 75000, "2016-11-23", "2017-01-23");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_3", "books", 50000, "2016-12-03", "2017-02-03");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_4", "music", 100000, "2016-05-03", "2016-07-03");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_5", "design",100000, "2016-09-03", "2016-12-03");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_6", "charity", 100000, "2016-10-23", "2016-12-23");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_7", "art", 100000, "2016-06-03", "2016-12-03");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_8", "charity", 100000, "2017-02-07", "2017-04-07");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_9", "charity", 100000, "2016-01-05", "2017-03-05");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("project_10", "music", 100000, "2016-10-03", "2017-04-03");

INSERT INTO users (name, age) VALUES ("Jose", 29);
INSERT INTO users (name, age) VALUES ("Maria", 33);
INSERT INTO users (name, age) VALUES ("Laura", 29);
INSERT INTO users (name, age) VALUES ("Manuel", 28);
INSERT INTO users (name, age) VALUES ("Joseph", 33);
INSERT INTO users (name, age) VALUES ("Pablo", 45);
INSERT INTO users (name, age) VALUES ("Lucas", 27);
INSERT INTO users (name, age) VALUES ("Alex", 30);
INSERT INTO users (name, age) VALUES ("Christian", 29);
INSERT INTO users (name, age) VALUES ("Gabriela", 40);
INSERT INTO users (name, age) VALUES ("Andrea", 29);
INSERT INTO users (name, age) VALUES ("Michelle", 32);
INSERT INTO users (name, age) VALUES ("Miguel", 29);
INSERT INTO users (name, age) VALUES ("Lisa", 29);
INSERT INTO users (name, age) VALUES ("Rafael", 32);
INSERT INTO users (name, age) VALUES ("Andrew", 34);
INSERT INTO users (name, age) VALUES ("Juan", 36);
INSERT INTO users (name, age) VALUES ("Nicolas", 32);
INSERT INTO users (name, age) VALUES ("Robert", 45);
INSERT INTO users (name, age) VALUES ("Jaime", 34);


INSERT INTO pledges (amount) VALUES (300);
INSERT INTO pledges (amount) VALUES (500);
INSERT INTO pledges (amount) VALUES (100);
INSERT INTO pledges (amount) VALUES (75);
INSERT INTO pledges (amount) VALUES (600);
INSERT INTO pledges (amount) VALUES (3000);
INSERT INTO pledges (amount) VALUES (400);
INSERT INTO pledges (amount) VALUES (90);
INSERT INTO pledges (amount) VALUES (140);
INSERT INTO pledges (amount) VALUES (150);
INSERT INTO pledges (amount) VALUES (250);
INSERT INTO pledges (amount) VALUES (500);
INSERT INTO pledges (amount) VALUES (1000);
INSERT INTO pledges (amount) VALUES (440);
INSERT INTO pledges (amount) VALUES (650);
INSERT INTO pledges (amount) VALUES (200);
INSERT INTO pledges (amount) VALUES (300);
INSERT INTO pledges (amount) VALUES (300);
INSERT INTO pledges (amount) VALUES (300);
INSERT INTO pledges (amount) VALUES (300);
INSERT INTO pledges (amount) VALUES (300);
INSERT INTO pledges (amount) VALUES (400);
INSERT INTO pledges (amount) VALUES (300);
INSERT INTO pledges (amount) VALUES (550);
INSERT INTO pledges (amount) VALUES (5500);
INSERT INTO pledges (amount) VALUES (3000);
INSERT INTO pledges (amount) VALUES (350);
INSERT INTO pledges (amount) VALUES (30);
INSERT INTO pledges (amount) VALUES (50);
INSERT INTO pledges (amount) VALUES (300);
